config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  root 'kudos#index'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  namespace :admin do
    root to: 'pages#dashboard'
    resources :kudos
    resources :online_codes, only: %i[index new create destroy edit update] do
      collection { post :import }
      collection { get :export }
    end
    resources :company_values
    resources :rewards do
      collection { post :import }
      collection { get :export }
    end
    resources :categories
    resources :deliveries, only: %i[update]
    resources :orders, only: %i[index] do
      collection { get :export }
    end
    resources :employees do
      patch 'add_kudos_for_all'
    end
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :title, :description, :price, presence: true
  validates :photo, file_content_type: { allow: ['image/jpeg', 'image/png'] }

  has_one_attached :photo

  has_many :orders, dependent: :nullify
  has_many :online_codes, dependent: :destroy
  has_many :category_rewards, dependent: :destroy
  has_many :categories, through: :category_rewards

  enum delivery_method: { online: 'online', post: 'post' }

  scope :in_stock, -> { where('available_items > 0').or(where('online_codes_count > 0')) }

  def number_of_available_items
    delivery_method == 'online' ? online_codes_count : available_items
  end
end

app/controllers/admin/rewards_controller.rb
# frozen_string_literal: true

require 'csv'

module Admin
  class RewardsController < AdminController
    def index
      @rewards = Reward.all.with_attached_photo.order(:title)
    end

    def edit
      @reward = Reward.find(params[:id])
    end

    def new
      @reward = Reward.new
    end

    def create
      @reward = Reward.new(reward_params)
      @reward.slug = @reward.title.parameterize
      if @reward.save
        redirect_to admin_rewards_path, notice: 'Reward was successfully created.'
      else
        render :new
      end
    end

    def update
      @reward = Reward.find(params[:id])
      @reward.slug = reward_params[:title].parameterize
      if @reward.update(reward_params)
        redirect_to admin_rewards_path, notice: 'Reward was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @reward = Reward.find(params[:id])
      @reward.destroy
      redirect_to admin_rewards_path, notice: 'Reward was successfully destroyed.'
    end

    def export
      @rewards = Reward.all.order(:title)

      response.headers['Content-Type'] = 'text/csv'
      response.headers['Content-Disposition'] = "attachment; filename=rewards_#{Time.zone.now.strftime('%y%m%d_%H-%M-%S')}.csv"
      render template: 'admin/rewards/export', handlers: [:erb], formats: [:csv]
    end

    def import
      import_service = ImportRewardsCsvService.new(params)

      if import_service.call
        redirect_to admin_rewards_path, notice: 'Rewards imported.'
      else
        redirect_to admin_rewards_path, notice: import_service.errors.join(', ')
      end
    end

    private

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :photo, :delivery_method, :available_items, category_ids: [])
    end
  end
end

app/controllers/rewards_controller.rb
# frozen_string_literal: true

class RewardsController < ApplicationController
  before_action :authenticate_employee!

  REWARDS_PER_PAGE = 10

  def index
    page = params[:page].to_i || 0
    count_pages = (RewardSearch.new(params).results.count.to_f / REWARDS_PER_PAGE).ceil
    rewards = RewardSearch.new(params).results.limit(REWARDS_PER_PAGE).offset(page * REWARDS_PER_PAGE)
    categories = Category.all
    render 'index', locals: { page: page, count_pages: count_pages, rewards: rewards, categories: categories }
  end

  def show
    @reward = Reward.find(params[:id])
  end
end

app/views/admin/rewards/_form.html.erb
<%= form_with(model: [:admin, @reward ]) do |form| %>
  <% if @reward.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reward.errors.count, "error") %> prohibited this reward from being saved:</h2>

      <ul>
        <% @reward.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="mb-3">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="field">
  <%= form.label :description %>
  <%= form.text_area :description %>
</div>

<div class="field">
  <%= form.label :price %>
  <%= form.number_field :price %>
</div>

  <% if @reward.delivery_method != 'online' %>
  <div class="field">
    <%= form.label :available_items %>
    <%= form.number_field :available_items %>
  </div>
<% end %>

<div class="field">
  <%= form.label :delivery_method %>
  <%= form.select(:delivery_method, options_for_select(Reward.delivery_methods, selected: form.object.delivery_method_before_type_cast)) %>
</div>

<div class="field">
  <%= form.label 'Categories' %>
  <br />
  <%= form.collection_check_boxes :category_ids, Category.all, :id, :title do |b| %>
    <label class="form-check-label">
      <%= b.check_box %>
      <%= b.label %>
    </label><br />
  <% end %>
</div>

<div class="field">
  <%= form.label :photo %>
  <%= form.file_field :photo %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/admin/rewards/edit.html.erb
<h1>Editing Reward</h1>

<%= render 'form'%>

<%= link_to 'Back', admin_rewards_path %>

app/views/admin/rewards/export.csv.erb
<% headers = ['slug', 'title', 'description', 'price', 'delivery_method'] -%><%= CSV.generate_line headers -%>
<% @rewards.each do |reward| -%><%= CSV.generate_line([reward.slug, reward.title, reward.description, reward.price, reward.delivery_method]).html_safe -%><% end -%>

app/views/admin/rewards/index.html.erb
<h1>Manage Rewards</h1>

<%= link_to 'Download all rewards as CSV', export_admin_rewards_path, class: 'btn btn-outline-success btn-sm' %>

<%= form_tag import_admin_rewards_path, multipart: true, class: 'form-inline' do %>
  <div class="form-group">
    <%= file_field_tag :file %>
  </div>
  
  <div class="form-group">
    <%= submit_tag "Import CSV", class: 'btn btn-outline-success btn-sm' %>
  </div>
<% end %>
<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <tr>
      <th>Title</th>
      <th>Slug</th>
      <th class="col-md-8">Description</th>
      <th>Price</th>
      <th>Delivery Method</th>
      <th>Available</th>
      <th>Photo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @rewards.each do |reward| %>
      <tr>
        <td><%= reward.title %></td>
        <td><%= reward.slug %></td>
        <td><%= reward.description %></td>
        <td><%= reward.price %></td>
        <td><%= reward.delivery_method %></td>
        <td><%= reward.number_of_available_items %></td>
        <th><% if reward.photo.attached?%> <%= image_tag reward.photo, height: '50px' %> <% end %></th>
        <td>
          <%= link_to 'Edit', edit_admin_reward_path(reward), class: 'btn btn-outline-primary btn-sm' %>
          <%= link_to 'Delete', admin_reward_path(reward), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reward', new_admin_reward_path, class: 'btn btn-success' %>

app/views/admin/rewards/new.html.erb
<h1>New Reward</h1>

<%= render 'form'%>

<%= link_to 'Back', admin_rewards_path %>