config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  root 'kudos#index'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  namespace :admin do
    root to: 'pages#dashboard'
    resources :kudos
    resources :online_codes, only: %i[index new create destroy edit update] do
      collection { post :import }
      collection { get :export }
    end
    resources :company_values
    resources :rewards do
      collection { post :import }
      collection { get :export }
    end
    resources :categories
    resources :deliveries, only: %i[update]
    resources :orders, only: %i[index] do
      collection { get :export }
    end
    resources :employees do
      patch 'add_kudos_for_all'
    end
  end
end

app/models/employee.rb
# frozen_string_literal: true

class Employee < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :given_kudos, class_name: 'Kudo', foreign_key: 'giver_id', dependent: :destroy, inverse_of: :giver
  has_many :received_kudos, class_name: 'Kudo', foreign_key: 'receiver_id', dependent: :destroy, inverse_of: :receiver
  has_many :orders, dependent: :destroy
  has_many :rewards, through: :orders
  has_one :address, dependent: :destroy

  validates :first_name, :last_name, presence: true

  def points
    received_kudos.count - rewards.sum(:price).to_i
  end

  def full_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    else
      email
    end
  end
end

app/controllers/admin/employees_controller.rb
# frozen_string_literal: true

module Admin
  class EmployeesController < AdminController
    def index
      @employees = Employee.all
    end

    def edit
      @employee = Employee.find(params[:id])
    end

    def update
      @employee = Employee.find(params[:id])
      check_password_params = employee_params
      check_password_params.delete(:password) if check_password_params[:password].blank?
      if @employee.update(check_password_params)
        redirect_to admin_employees_path, notice: 'Employee was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @employee = Employee.find(params[:id])
      @employee.destroy
      redirect_to admin_employees_path, notice: 'Employee was successfully destroyed.'
    end

    def add_kudos_for_all
      if amount_param.between? 1, 20
        begin
          ActiveRecord::Base.transaction do
            @employees = Employee.find_each
            @employees.each do |employee|
              employee.number_of_available_kudos += amount_param
              employee.save!
            end
          end
          redirect_to admin_employees_path, notice: "Added #{amount_param} points to every employee"
        rescue ActiveRecord::RecordInvalid => e
          render :new, notice: e.message
        end
      else
        redirect_to admin_employees_path, notice: 'Number must be between 1 and 20'
      end
    end

    private

    def amount_param
      params[:amount].to_i
    end

    def employee_params
      params.require(:employee).permit(:first_name, :last_name, :email, :password)
    end
  end
end

app/views/admin/employees/_form.html.erb
<%= form_with(model: [:admin, @employee ]) do |f| %>

  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
        <% @employee.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field w-50">
      <%= f.label :first_name %><br />
      <%= f.text_field :first_name, class: 'form-control' %>
    </div>  
    
    <div class="field w-50">
      <%= f.label :last_name %><br />
      <%= f.text_field :last_name, class: 'form-control' %>
    </div>

  <div class="field w-50">
    <%= f.label :email %><br />
    <%= f.email_field :email, class: 'form-control' %>
  </div>
<br/>

  <div class="field w-50">
    <%= f.label :password %> <i>(leave blank if you don't want to change it)</i><br />
    <%= f.password_field :password, autocomplete: "new-password", class: 'form-control' %>
    <% if @minimum_password_length %>
      <em><%= @minimum_password_length %> characters minimum</em>
      <br/>
    <% end %>
  </div>

  <div class="actions">
    <%= f.submit "Update", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/admin/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form'%>

<%= link_to 'Back', admin_employees_path %>

app/views/admin/employees/index.html.erb
<h2> Add number of available kudos to all employees</h2>
<br/>

<%= form_with url: admin_employee_add_kudos_for_all_path(@employees), method: :patch do |f| %>
  <%= f.number_field :amount, in: 1..20, value: 1 %>
  <%= f.submit "Add points" %>
<% end %>
<br/>

<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <tr>
      <th>Employees</th>
      <th>Points</th>
      <th>Number of Available Kudos</th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr data-user-email="<%= employee.email %>">
        <td><%= employee.full_name %></td>
        <td><%= employee.points %></td>
        <td><%= employee.number_of_available_kudos %></td>
        <td><%= link_to 'Edit', edit_admin_employee_path(employee), class: 'btn btn-outline-primary btn-sm' %></td>
        <td><%= link_to 'Destroy', admin_employee_path(employee), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>