config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  root 'kudos#index'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  namespace :admin do
    root to: 'pages#dashboard'
    resources :kudos
    resources :online_codes, only: %i[index new create destroy edit update] do
      collection { post :import }
      collection { get :export }
    end
    resources :company_values
    resources :rewards do
      collection { post :import }
      collection { get :export }
    end
    resources :categories
    resources :deliveries, only: %i[update]
    resources :orders, only: %i[index] do
      collection { get :export }
    end
    resources :employees do
      patch 'add_kudos_for_all'
    end
  end
end

app/models/reward.rb
# frozen_string_literal: true

class Reward < ApplicationRecord
  validates :price, numericality: { greater_than_or_equal_to: 1 }
  validates :title, :description, :price, presence: true
  validates :photo, file_content_type: { allow: ['image/jpeg', 'image/png'] }

  has_one_attached :photo

  has_many :orders, dependent: :nullify
  has_many :online_codes, dependent: :destroy
  has_many :category_rewards, dependent: :destroy
  has_many :categories, through: :category_rewards

  enum delivery_method: { online: 'online', post: 'post' }

  scope :in_stock, -> { where('available_items > 0').or(where('online_codes_count > 0')) }

  def number_of_available_items
    delivery_method == 'online' ? online_codes_count : available_items
  end
end

app/controllers/admin/rewards_controller.rb
# frozen_string_literal: true

require 'csv'

module Admin
  class RewardsController < AdminController
    def index
      @rewards = Reward.all.with_attached_photo.order(:title)
    end

    def edit
      @reward = Reward.find(params[:id])
    end

    def new
      @reward = Reward.new
    end

    def create
      @reward = Reward.new(reward_params)
      @reward.slug = @reward.title.parameterize
      if @reward.save
        redirect_to admin_rewards_path, notice: 'Reward was successfully created.'
      else
        render :new
      end
    end

    def update
      @reward = Reward.find(params[:id])
      @reward.slug = reward_params[:title].parameterize
      if @reward.update(reward_params)
        redirect_to admin_rewards_path, notice: 'Reward was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @reward = Reward.find(params[:id])
      @reward.destroy
      redirect_to admin_rewards_path, notice: 'Reward was successfully destroyed.'
    end

    def export
      @rewards = Reward.all.order(:title)

      response.headers['Content-Type'] = 'text/csv'
      response.headers['Content-Disposition'] = "attachment; filename=rewards_#{Time.zone.now.strftime('%y%m%d_%H-%M-%S')}.csv"
      render template: 'admin/rewards/export', handlers: [:erb], formats: [:csv]
    end

    def import
      import_service = ImportRewardsCsvService.new(params)

      if import_service.call
        redirect_to admin_rewards_path, notice: 'Rewards imported.'
      else
        redirect_to admin_rewards_path, notice: import_service.errors.join(', ')
      end
    end

    private

    def reward_params
      params.require(:reward).permit(:title, :description, :price, :photo, :delivery_method, :available_items, category_ids: [])
    end
  end
end

app/controllers/rewards_controller.rb
# frozen_string_literal: true

class RewardsController < ApplicationController
  before_action :authenticate_employee!

  REWARDS_PER_PAGE = 10

  def index
    page = params[:page].to_i || 0
    count_pages = (RewardSearch.new(params).results.count.to_f / REWARDS_PER_PAGE).ceil
    rewards = RewardSearch.new(params).results.limit(REWARDS_PER_PAGE).offset(page * REWARDS_PER_PAGE)
    categories = Category.all
    render 'index', locals: { page: page, count_pages: count_pages, rewards: rewards, categories: categories }
  end

  def show
    @reward = Reward.find(params[:id])
  end
end

app/views/rewards/index.html.erb
<h1>Available Rewards:</h1>

<div class="nav ms-auto w-100">
  <%= link_to 'All', rewards_path, class: 'btn btn-outline-secondary' %>
  <% categories.each do |category| %>
      <%= link_to category.title, rewards_path(category: category.title), class: 'btn btn-outline-secondary' %>
  <% end %>
</div>

<table class="table table-striped table-hover" id="rewards_table">
  <thead class="table-secondary">
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Delivery Method</th>
      <th>Available</th>
      <th>Photo</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% rewards.each do |reward| %>
      <tr data-reward-id="<%= reward.id %>">
        <td><%= reward.title %></td>
        <td><%= reward.price %></td>
        <td><%= reward.delivery_method %></td>
        <td><%= reward.number_of_available_items %></td>
        <th><% if reward.photo.attached? %> <%= image_tag reward.photo, width: '80px' %> <% end %></th>
        <td><%= link_to "Buy", new_order_path(reward: reward,), method: :get, class: "btn btn-success btn-sm" %><%= link_to 'Show', reward_path(reward), class: 'btn btn-outline-primary btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= render 'pages/pagination', page: page, count_pages: count_pages %>

app/views/rewards/show.html.erb
<div class="d-flex w-50 ">
  <div class="container p-2">
    <div class="card-deck mb-3 text-center">
      <div class="card mb-4 shadow-sm">
        <div class="card-header">
          <h4 class="my-0 font-weight-normal">Reward details</h4>
        </div>
        <div class="card-body">
          <ul class="list-unstyled mt-3 mb-4">
            <li><h4>Title: <%= @reward.title %></h4></li>
            <% if @reward.photo.attached? %>
              <li>Photo: <%= image_tag @reward.photo, width: '200px' %></li>
            <% end %>
            <li>Description: <%= @reward.description %></li>
            <li>Price: <%= @reward.price %></li>
            <li>Categories:</li>
            <ul>
              <% @reward.categories.each do |category| %>
              <li><%= category.title %></li>
              <% end %>
            </ul>
          </ul>
        </div>
      </div>
    </div>
    <div class="d-flex justify-content-end">
      <%= link_to "Buy", orders_path(reward: @reward,), method: :post, class: "btn btn-success" %>
      <%= link_to 'Back', rewards_path, class: 'btn btn-secondary' %>
    </div>
  </div>
</div>