config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :admin_users, path: 'admin'
  devise_for :employees, path: 'employees'

  root 'kudos#index'

  resources :kudos
  resources :rewards, only: %i[index show]
  resources :orders, only: %i[index new create]

  namespace :admin do
    root to: 'pages#dashboard'
    resources :kudos
    resources :online_codes, only: %i[index new create destroy edit update] do
      collection { post :import }
      collection { get :export }
    end
    resources :company_values
    resources :rewards do
      collection { post :import }
      collection { get :export }
    end
    resources :categories
    resources :deliveries, only: %i[update]
    resources :orders, only: %i[index] do
      collection { get :export }
    end
    resources :employees do
      patch 'add_kudos_for_all'
    end
  end
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  validates :title, presence: true

  has_many :category_rewards, dependent: :destroy
  has_many :rewards, through: :category_rewards
end

app/controllers/admin/categories_controller.rb
# frozen_string_literal: true

module Admin
  class CategoriesController < AdminController
    def index
      @categories = Category.all
    end

    def edit
      @category = Category.find(params[:id])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to admin_categories_path, notice: 'Category was successfully created.'
      else
        render :new
      end
    end

    def update
      @category = Category.find(params[:id])
      if @category.update(category_params)
        redirect_to admin_categories_path, notice: 'Category was successfully updated.'
      else
        render :edit
      end
    end

    def destroy
      @category = Category.find(params[:id])
      if @category.rewards.any?
        redirect_to admin_categories_path, notice: 'Category must be empty in order to delete it.'
      else
        @category.destroy
        redirect_to admin_categories_path, notice: 'Category was successfully destroyed.'
      end
    end

    private

    def category_params
      params.require(:category).permit(:title)
    end
  end
end

app/views/admin/categories/_form.html.erb
<%= form_with(model: [:admin, @category ]) do |form| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this kudo from being saved:</h2>

      <ul>
        <% @category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
<div class="mb-3">
  <%= form.label :title %>
  <%= form.text_field :title %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/admin/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form'%>

<%= link_to 'Show', admin_category_path(@category) %> |
<%= link_to 'Back', admin_categories_path %>

app/views/admin/categories/index.html.erb
<h1>Manage Categories</h1>

<table class="table table-striped table-hover">
  <thead class="table-secondary">
    <tr>
      <th>Title</th>
      <th>Count Rewards</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.title %></td>
        <td><%= category.rewards.count   %></td>
        <td><%= link_to 'Edit', edit_admin_category_path(category), class: 'btn btn-outline-primary btn-sm' %><%= link_to 'Destroy', admin_category_path(category), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_admin_category_path, class: 'btn btn-success' %>

app/views/admin/categories/new.html.erb
<h1>New Kudo</h1>

<%= render 'form'%>

<%= link_to 'Back', admin_kudos_path %>